# Generated by Django 5.0.6 on 2026-06-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_calle', models.CharField(blank=True, max_length=10, null=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('dpto', models.CharField(blank=True, max_length=10, null=True)),
                ('manzana', models.CharField(blank=True, max_length=10, null=True)),
                ('casa', models.CharField(blank=True, max_length=10, null=True)),
                ('nro_casa', models.CharField(blank=True, max_length=10, null=True)),
                ('pieza', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('localidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'domicilio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=256, null=True)),
                ('apellido', models.CharField(blank=True, max_length=256, null=True)),
                ('dni', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('tipo_dni', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
    ]
