# Generated by Django 5.0.6 on 2026-06-20 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_year_month', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_year', models.IntegerField(blank=True, null=True)),
                ('updated_year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('matricula', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'profesionales',
                'managed': True,
            },
        ),
    ]
