# Generated by Django 5.0.6 on 2026-06-20 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('personas', '0001_initial'),
        ('tutores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='domicilio',
            field=models.ForeignKey(db_column='id_domicilio', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.domicilio'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='persona',
            field=models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(db_column='id_responsable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutores.tutor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
