# Generated by Django 6.0.5 on 2026-06-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="adulto_apellido",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="adulto_dni",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="adulto_nombre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="adulto_tipo_documento",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="consentimiento_aceptado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paciente",
            name="fecha_consentimiento",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
