# Generated by Django 5.0.6 on 2026-06-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_adulto_apellido_paciente_adulto_dni_and_more'),
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='adulto_apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='adulto_dni',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='adulto_nombre',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='adulto_tipo_documento',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='persona',
            field=models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_persona', to='personas.persona'),
        ),
    ]
