# Generated by Django 5.0.6 on 2026-06-22 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_paciente_adulto_apellido_and_more'),
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='persona',
            field=models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona'),
        ),
    ]
