# Generated by Django 6.0.5 on 2026-08-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_alter_escuela_options'),
        ('pacientes', '0005_paciente_celular_paciente_telefono_fijo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='escuelas.escuela'),
        ),
    ]
