# Generated by Django 6.0.5 on 2026-06-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matriculas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("tipo", models.CharField(max_length=20)),
                (
                    "nombre_completo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "matriculas",
                "managed": False,
            },
        ),
    ]
