# Generated by Django 6.0.5 on 2026-06-09 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_usuarios_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuarios",
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_year",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_year_month",
                    models.CharField(
                        blank=True, db_index=True, max_length=7, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_year", models.IntegerField(blank=True, null=True)),
                (
                    "updated_year_month",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=191)),
                ("icon", models.CharField(blank=True, max_length=64, null=True)),
                ("color", models.CharField(blank=True, max_length=9, null=True)),
                ("type", models.CharField(max_length=32)),
                ("category", models.CharField(blank=True, max_length=32, null=True)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "actions",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_year",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_year_month",
                    models.CharField(
                        blank=True, db_index=True, max_length=7, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_year", models.IntegerField(blank=True, null=True)),
                (
                    "updated_year_month",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("action_name", models.CharField(max_length=64)),
                ("used_at", models.DateTimeField(db_index=True)),
                ("context", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "action_logs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RoleAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_year",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_year_month",
                    models.CharField(
                        blank=True, db_index=True, max_length=7, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_year", models.IntegerField(blank=True, null=True)),
                (
                    "updated_year_month",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "action",
                    models.ForeignKey(
                        db_column="action_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_actions",
                        to="authentication.action",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_actions",
                        to="authentication.roles",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "role_actions",
                "managed": True,
                "unique_together": {("role", "action")},
            },
        ),
        migrations.CreateModel(
            name="UserActionOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_year",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_year_month",
                    models.CharField(
                        blank=True, db_index=True, max_length=7, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_year", models.IntegerField(blank=True, null=True)),
                (
                    "updated_year_month",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[("grant", "grant"), ("deny", "deny")], max_length=8
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        db_column="action_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="authentication.action",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_action_overrides",
                "managed": True,
                "unique_together": {("user", "action")},
            },
        ),
    ]
