# Generated by Django 5.0.6 on 2026-06-20 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteFamiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_year_month', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_year', models.IntegerField(blank=True, null=True)),
                ('updated_year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('problemas_salud', models.CharField(blank=True, max_length=10, null=True)),
                ('detalle_problema_salud', models.CharField(blank=True, max_length=255, null=True)),
                ('familiar_con_muerte_subita', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'antecedentesfamiliares',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AntecedentePersonal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_year_month', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_year', models.IntegerField(blank=True, null=True)),
                ('updated_year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nacio_prematuro', models.CharField(default='NO', max_length=10)),
                ('peso_nacimiento', models.CharField(default='0', max_length=10)),
                ('convulsiones_epilepsia', models.CharField(default='NO', max_length=10)),
                ('mareos_desmayos', models.CharField(default='NO', max_length=10)),
                ('infecciones_urinarias', models.CharField(default='NO', max_length=10)),
                ('asma_espasmos', models.CharField(default='NO', max_length=10)),
                ('tuberculosis', models.CharField(default='NO', max_length=10)),
                ('diabetes', models.CharField(default='NO', max_length=10)),
                ('hipertension', models.CharField(default='NO', max_length=10)),
                ('cardiopatia_congenita', models.CharField(default='NO', max_length=10)),
                ('traumatismo_internacion', models.CharField(default='NO', max_length=255)),
                ('diarrea_frecuente', models.CharField(default='NO', max_length=255)),
                ('infecciones_oido', models.CharField(default='NO', max_length=255)),
                ('causa_hospitalizacion', models.CharField(default='NO', max_length=255)),
                ('rabia_tratamiento', models.CharField(default='NO', max_length=255)),
                ('descripcion_tratamiento', models.CharField(default='NINGUNO', max_length=255)),
                ('ultima_consulta_medica', models.CharField(default='NINGUNA', max_length=255)),
                ('otros_problemas_salud', models.CharField(default='NINGUNO', max_length=255)),
                ('primera_menstruacion', models.CharField(default='NO', max_length=255)),
                ('edad_primera_menstruacion', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'antecedentespersonales',
                'managed': True,
            },
        ),
    ]
