# Generated by Django 5.0.6 on 2026-06-22 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antecedentes', '0002_initial'),
        ('tutores', '0003_tutor_consentimiento_aceptado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteFamiliarTutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_year_month', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_year', models.IntegerField(blank=True, null=True)),
                ('updated_year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('problema_salud_importante', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('no_sabe', 'No sabe')], max_length=10, null=True)),
                ('problema_salud_cual', models.TextField(blank=True, null=True)),
                ('muerte_subita_familiar', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('no_sabe', 'No sabe')], max_length=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.OneToOneField(db_column='id_tutor', on_delete=django.db.models.deletion.CASCADE, related_name='antecedente_familiar', to='tutores.tutor')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'antecedente familiar del tutor',
                'verbose_name_plural': 'antecedentes familiares del tutor',
                'db_table': 'antecedentes_familiares_tutor',
                'managed': True,
            },
        ),
    ]
