# Generated by Django 6.0.5 on 2026-08-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antecedentes', '0003_antecedentefamiliartutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedentepersonal',
            old_name='rabia_tratamiento',
            new_name='tratamiento_actual',
        ),
    ]
