# Generated by Django 6.0.5 on 2026-08-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antecedentes', '0004_rename_rabia_tratamiento_antecedentepersonal_tratamiento_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentepersonal',
            name='internacion_previa',
            field=models.CharField(default='NO', max_length=255),
        ),
    ]
