# Generated by Django 5.0.6 on 2026-06-20 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_year_month', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_year', models.IntegerField(blank=True, null=True)),
                ('updated_year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nombre_escuela', models.CharField(db_column='nombre_escuela', max_length=100)),
                ('ambito_escuela', models.CharField(db_column='ambito_escuela', max_length=20)),
                ('sector_gestion', models.CharField(db_column='sector_gestion', max_length=20)),
                ('modalidad_educativa', models.CharField(db_column='modalidad_educativa', max_length=10)),
                ('escuela_bilingue', models.BooleanField(db_column='escuela_bilingue')),
                ('rural_plurigrado', models.BooleanField(db_column='rural_plurigrado')),
            ],
            options={
                'db_table': 'escuelas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObservacionEscuela',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_year_month', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_year', models.IntegerField(blank=True, null=True)),
                ('updated_year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dificultad_comunicacion', models.CharField(db_column='dificultad_comunicacion', max_length=255)),
                ('esta_bajo_tratamiento', models.BooleanField(db_column='bajo_tratamiento')),
                ('preocupaciones', models.CharField(db_column='preocupaciones', max_length=255)),
            ],
            options={
                'db_table': 'observacionEscuela',
                'managed': True,
            },
        ),
    ]
