# Generated by Django 6.0.5 on 2026-06-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escuela',
            options={'ordering': ['nombre'], 'verbose_name': 'escuela', 'verbose_name_plural': 'escuelas'},
        ),
    ]
