# Generated by Django 5.0.6 on 2026-06-20 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escuela',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observacionescuela',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observacionescuela',
            name='escuela',
            field=models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.escuela'),
        ),
        migrations.AddField(
            model_name='observacionescuela',
            name='paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='observacionescuela',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='observacionescuela',
            unique_together={('paciente', 'escuela')},
        ),
    ]
