# Generated by Django 6.0.5 on 2026-09-07 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_alter_escuela_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('escuela', 'sala_grado_anio', 'division', 'ciclo_lectivo'), name='uq_curso_escuela_grado_division_ciclo', nulls_distinct=False),
        ),
    ]
