# Generated by Django 6.0.5 on 2026-09-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0003_curso_uq_curso_escuela_grado_division_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='modalidad_educativa',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
