# Generated by Django 6.0.5 on 2026-06-23 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operativos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operativoalumno",
            name="escuela_bajo_tratamiento",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operativoalumno",
            name="escuela_completado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operativoalumno",
            name="escuela_dificultad_lenguaje",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operativoalumno",
            name="escuela_preocupa_detalle",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="operativoalumno",
            name="escuela_preocupa_salud",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EvaluacionMedica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_year",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_year_month",
                    models.CharField(
                        blank=True, db_index=True, max_length=7, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_year", models.IntegerField(blank=True, null=True)),
                (
                    "updated_year_month",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("fecha_evaluacion", models.DateTimeField(blank=True, null=True)),
                ("examen_realizado", models.BooleanField(default=False)),
                (
                    "motivo_no_examen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("negativa_familiar", "Negativa familiar"),
                            ("negativa_nino", "Negativa del niño/adolescente"),
                            ("ausente", "Ausente el día del examen"),
                            ("otros", "Otros"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "lugar_examen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("escuela", "En la escuela"),
                            ("centro_salud", "En el centro de salud"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("trajo_carnet", models.BooleanField(default=False)),
                ("carnet_completo", models.BooleanField(default=False)),
                ("vacunas_aplicadas", models.TextField(blank=True, default="")),
                ("vacunas_indicadas", models.TextField(blank=True, default="")),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "talla",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "imc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "percentil_talla",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("menor_3", "Menor a 3"),
                            ("mayor_igual_3", "Mayor o igual a 3"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "percentil_imc",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("menor_3", "Menor a 3 (emaciación)"),
                            ("entre_3_9", "Entre 3 y 9 (riesgo de bajo peso)"),
                            ("entre_10_84", "Entre 10 y 84 (normal)"),
                            ("entre_85_97", "Entre 85 y 97 (sobrepeso)"),
                            ("mayor_97", "Mayor a 97 (obesidad)"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("pas", models.IntegerField(blank=True, null=True)),
                ("pad", models.IntegerField(blank=True, null=True)),
                (
                    "presion_clasificacion",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("agudeza_evaluada", models.BooleanField(default=False)),
                (
                    "ojo_derecho",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "ojo_izquierdo",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("usa_lentes", models.BooleanField(default=False)),
                ("audiometria_realizada", models.BooleanField(default=False)),
                (
                    "audiometria_resultado",
                    models.CharField(
                        blank=True,
                        choices=[("pasa", "Pasa"), ("no_pasa", "No pasa")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("hallazgos", models.JSONField(blank=True, default=dict)),
                ("derivaciones", models.JSONField(blank=True, default=dict)),
                ("completada", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operativo_alumno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluacion_medica",
                        to="operativos.operativoalumno",
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluaciones_medicas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "evaluación médica",
                "verbose_name_plural": "evaluaciones médicas",
                "db_table": "operativos_evaluaciones_medicas",
            },
        ),
        migrations.CreateModel(
            name="EvaluacionOdontologica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_year",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_year_month",
                    models.CharField(
                        blank=True, db_index=True, max_length=7, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_year", models.IntegerField(blank=True, null=True)),
                (
                    "updated_year_month",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("fecha_evaluacion", models.DateTimeField(blank=True, null=True)),
                (
                    "salud_bucal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("con_hallazgos", "Con hallazgos"),
                            ("sin_hallazgos", "Sin hallazgos"),
                            ("no_eval", "No se evaluó"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("lesiones_tejidos_blandos", models.BooleanField(default=False)),
                ("maloclusion", models.BooleanField(default=False)),
                ("fluorosis", models.BooleanField(default=False)),
                ("caries", models.BooleanField(default=False)),
                ("otros", models.TextField(blank=True, default="")),
                ("topicacion_fluor", models.BooleanField(default=False)),
                ("ensenanza_cepillado", models.BooleanField(default=False)),
                ("alta_basica", models.BooleanField(default=False)),
                ("cpo_c", models.IntegerField(blank=True, null=True)),
                ("cpo_p", models.IntegerField(blank=True, null=True)),
                ("cpo_o", models.IntegerField(blank=True, null=True)),
                ("ceo_c", models.IntegerField(blank=True, null=True)),
                ("ceo_e", models.IntegerField(blank=True, null=True)),
                ("ceo_o", models.IntegerField(blank=True, null=True)),
                ("odontograma", models.JSONField(blank=True, default=dict)),
                ("completada", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operativo_alumno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluacion_odontologica",
                        to="operativos.operativoalumno",
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluaciones_odontologicas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "evaluación odontológica",
                "verbose_name_plural": "evaluaciones odontológicas",
                "db_table": "operativos_evaluaciones_odontologicas",
            },
        ),
    ]
