# Generated by Django 6.0.5 on 2026-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0002_operativoalumno_escuela_bajo_tratamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativoalumno',
            name='antecedentes_completado',
            field=models.BooleanField(default=False),
        ),
    ]
