# Generated by Django 6.0.5 on 2026-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0003_operativoalumno_antecedentes_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionmedica',
            name='antropometria_evaluada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionmedica',
            name='presion_evaluada',
            field=models.BooleanField(default=True),
        ),
    ]
