# Generated by Django 6.0.5 on 2026-09-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0004_evaluacionmedica_antropometria_evaluada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativoprofesional',
            name='rol_en_operativo',
            field=models.CharField(choices=[('medico', 'Médico'), ('odontologo', 'Odontólogo'), ('administrativo', 'Administrativo')], max_length=20),
        ),
    ]
