# Generated by Django 6.0.5 on 2026-09-28 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0006_cpo_ceo_a_checks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_year_month', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_year', models.IntegerField(blank=True, null=True)),
                ('updated_year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, db_column='id_actor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_documentos', to=settings.AUTH_USER_MODEL)),
                ('alumno', models.ForeignKey(blank=True, db_column='id_alumno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_documentos', to='operativos.operativoalumno')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operativo', models.ForeignKey(blank=True, db_column='id_operativo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_documentos', to='operativos.operativo')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_documentos',
            },
        ),
    ]
