from apps.antecedentes.models.antecedentefamiliar import AntecedenteFamiliar
from apps.antecedentes.models.antecedentefamiliartutor import AntecedenteFamiliarTutor
from apps.antecedentes.models.antecedentepersonal import AntecedentePersonal
