# Generated by Django 6.0.5 on 2026-06-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_action_actionrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="roles",
            field=models.ManyToManyField(
                related_name="usuarios",
                through="usuarios.RoleUsuario",
                through_fields=("id_user", "id_rol"),
                to="usuarios.rol",
            ),
        ),
    ]
