# Generated by Django 6.0.5 on 2026-08-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_alter_escuela_options'),
        ('usuarios', '0003_alter_usuario_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_escuela', to='escuelas.escuela'),
        ),
    ]
