# Generated by Django 6.0.5 on 2026-08-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Si es falso, la acción otorga permiso pero no aparece como tile del menú principal.'),
        ),
    ]
