# Generated by Django 5.0.6 on 2026-06-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='consentimiento_aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='fecha_consentimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
