# Generated by Django 6.0.5 on 2026-06-11 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_year",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_year_month",
                    models.CharField(
                        blank=True, db_index=True, max_length=7, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_year", models.IntegerField(blank=True, null=True)),
                (
                    "updated_year_month",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("borrador", "borrador"), ("firmado", "firmado")],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "altura_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("observaciones", models.TextField(blank=True, default="")),
                ("nna_dni", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "nna_nombre_completo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nna_edad", models.IntegerField(blank=True, null=True)),
                (
                    "profesional_nombre",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "matricula_firmante",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_emision", models.DateField(blank=True, null=True)),
                ("validez_hasta", models.DateField(blank=True, null=True)),
                ("firma_hash", models.CharField(blank=True, max_length=128, null=True)),
                ("timestamp_firma", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aptos",
                        to="patients.pacientes",
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aptos_firmados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "aptos",
                "managed": True,
            },
        ),
    ]
