# Generated by Django 6.0.5 on 2026-06-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentesfamiliares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemas_salud', models.CharField(blank=True, max_length=10, null=True)),
                ('detalle_problema_salud', models.CharField(blank=True, max_length=255, null=True)),
                ('familiar_con_muerte_subita', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'antecedentesfamiliares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Antecedentespersonales',
            fields=[
                ('id_antecedente', models.AutoField(primary_key=True, serialize=False)),
                ('nacio_prematuro', models.CharField(max_length=10)),
                ('peso_nacimiento', models.CharField(max_length=10)),
                ('convulsiones_epilepsia', models.CharField(max_length=10)),
                ('mareos_desmayos', models.CharField(max_length=10)),
                ('infecciones_urinarias', models.CharField(max_length=10)),
                ('asma_espasmos', models.CharField(max_length=10)),
                ('tuberculosis', models.CharField(max_length=10)),
                ('diabetes', models.CharField(max_length=10)),
                ('hipertension', models.CharField(max_length=10)),
                ('cardiopatia_congenita', models.CharField(max_length=10)),
                ('traumatismo_internacion', models.CharField(max_length=255)),
                ('diarrea_frecuente', models.CharField(max_length=255)),
                ('infecciones_oido', models.CharField(max_length=255)),
                ('causa_hospitalizacion', models.CharField(max_length=255)),
                ('rabia_tratamiento', models.CharField(max_length=255)),
                ('descripcion_tratamiento', models.CharField(max_length=255)),
                ('ultima_consulta_medica', models.CharField(max_length=255)),
                ('otros_problemas_salud', models.CharField(max_length=255)),
                ('primera_menstruacion', models.CharField(max_length=255)),
                ('edad_primera_menstruacion', models.IntegerField()),
            ],
            options={
                'db_table': 'antecedentespersonales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('tiene_cud', models.CharField(blank=True, max_length=2, null=True)),
                ('tipo_cobertura', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_cobertura', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'responsables',
                'managed': False,
            },
        ),
    ]
