# Generated by Django 6.0.5 on 2026-06-11 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consentimiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_year",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_year_month",
                    models.CharField(
                        blank=True, db_index=True, max_length=7, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_year", models.IntegerField(blank=True, null=True)),
                (
                    "updated_year_month",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "firma_tipo",
                    models.CharField(
                        choices=[
                            ("adulto_responsable", "Adulto responsable"),
                            ("nna_mayor_13", "NNA mayor de 13"),
                        ],
                        max_length=20,
                    ),
                ),
                ("adulto_nombre", models.CharField(max_length=200)),
                ("adulto_apellido", models.CharField(max_length=200)),
                ("adulto_tipo_documento", models.CharField(max_length=20)),
                ("adulto_dni", models.CharField(max_length=15)),
                ("firma_hash", models.CharField(max_length=128)),
                ("fecha_firma", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consentimientos",
                        to="patients.pacientes",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "consentimientos",
                "managed": True,
            },
        ),
    ]
