# Generated by Django 5.0.6 on 2026-06-20 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_year_month', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_year', models.IntegerField(blank=True, null=True)),
                ('updated_year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_calle', models.CharField(blank=True, max_length=10, null=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('dpto', models.CharField(blank=True, max_length=10, null=True)),
                ('manzana', models.CharField(blank=True, max_length=10, null=True)),
                ('casa', models.CharField(blank=True, max_length=10, null=True)),
                ('nro_casa', models.CharField(blank=True, max_length=10, null=True)),
                ('pieza', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('localidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'domicilio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_year_month', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_year', models.IntegerField(blank=True, null=True)),
                ('updated_year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=256, null=True)),
                ('apellido', models.CharField(blank=True, max_length=256, null=True)),
                ('dni', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('tipo_dni', models.CharField(blank=True, max_length=256, null=True)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'personas',
                'managed': True,
            },
        ),
    ]
